name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: gate-kawam, go-okuda, mochizuki-oss, mtmt-a, nait0-git, ozeki-gma, sano-chi, sasanuma7777, saseki-alt, shitou935, yfukusaka-a11y
